title: My Awesome Site
email: guoyang.shen@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my awesome site where I blog about my adventures in learning Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gshen-uh.github.io" # the base hostname & protocol for your site
github_username:  gshen-uh

# Build settings
theme: minima
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
plugins:
  - jekyll-feed
